name: .NET Framework CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1

    # Restoring NuGet dependencies using the correct path to the solution file
    - name: Install NuGet dependencies
      run: nuget restore "C:\Users\jorda\Documents\test script\Prog3bTestTwo\GitActionsTester\GitActionsTester.sln"  # Adjust path if necessary

    # Building the .NET project
    - name: Build project
      run: msbuild "C:\Users\jorda\Documents\test script\Prog3bTestTwo\GitActionsTester\GitActionsTester.sln" /p:Configuration=Release

